### ISSUE TITLE
Instead of 「by」, use 「assert」

### ISSUE THREAD

**Issue by linonetwo** [makeflow/turning#1]
Your interesting example looks like a stream:

```js
turning
  .turn(['session:not-logged-in'])
  .to(['session:logged-in'])
  .alias('login')
  .by(async ({page}) => {
    await page.click('.login-link');

    await page.type('input.username', 'admin');
    await page.type('input.password', '123456');

    await page.click('.login-submit-button');

    await page.waitForNavigation();
  });
```

But doesn't like a stream, it can't store intermediate steps.

Instead, if you make a transformation like this:
```js
const loginInput = turning
  .alias('login-input')
  .turn(['session:not-logged-in'])
  .by(async ({page}) => {
    await page.click('.login-link');

    await page.type('input.username', 'admin');
    await page.type('input.password', '123456');
  });

const commitLogin = loginInput
  .by(async ({page}) => {
    await page.click('.login-submit-button');
    await page.waitForNavigation();
  })
  .to(['session:logged-in']);

const abortLogin = loginInput
  .by(async ({page}) => {
    await page.click('.login-cancel-button');
    await page.waitForNavigation();
  })
  .to(['session:not-logged-in']);
```

In this way, you can make a usecase abstraction.

**Comment by vilicvane** [comment]
Actually `by()` can be chained with `test()`. The reason why I chose `by` is to emphisize the process of transformation, instead of the assertion.

And to be honest, I don't see much advatage brought by the stream-like interface. The same can be achieved by operation function abstractions. As the transformation is the one of the cores in turning, it would also be nice to make the obsolete/new states side-by-side. And that is also why `alias()` is chained after the states methods (`initialize`, `turn/to`, `spawn/to`).

**Comment by linonetwo** [comment]
Ok, it's a new way to write test, at least to me.

Waiting for your zhihu article about this.

**Comment by vilicvane** [comment]
@linonetwo haha I guess it is. Though I have seen several papers about this. Will write an article after writing more tests for our project.
